import com.jogamp.opengl.util.FPSAnimator;

/*
 * polymerframe.java
 *
 * Created on July 16, 2007, 11:44 PM
 */



/**
 *
 * @author  Eric
 */
public class StretchingMain extends javax.swing.JFrame {
    
    /** Creates new form polymerframe */
    public StretchingMain() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

    	jPanel1 = new stretchingAnimationPanel(100, 100);
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setText("100");
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        //jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 586, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 409, Short.MAX_VALUE)
        );

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel1.setText("Particles");

        jButton1.setText("Pause/Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Rate: 1-1000");

        jTextField2.setText("100");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(168, 168, 168)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(65, 65, 65))
                    .add(layout.createSequentialGroup()
                        .add(jTextField2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(23, 23, 23)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jButton1)
                        .add(jButton2))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(30, 30, 30))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(8, 8, 8)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        validate();
        pack();
    }

private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
    System.out.println("got the rate");
}

//reset operation
private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String particles = jTextField1.getText();
    if (!particles.matches("[0-9]+")) {
    	//if doesn't match just return
    	System.out.println("Not a valid particle number");
    	return;
    }
//    if (!jTextField2.getText().matches("[0-1]?[0-9]{0,3}?")) {
//    	//if text doesn't have 0/1 first digit or nothing, and 0-9 for 0 or 3 digits after return
//    	System.out.println("Not a valid rate number");
//    	return;
//    }
	if (jPanel1.animator.isAnimating()) {
    	jPanel1.animator.stop();
    }
	//First make the new animator 
	int fps = 80;  //get correct fps, so no lag
	jPanel1.animator = new FPSAnimator(jPanel1.renderableCanvas, fps, true);
	jPanel1.fps = fps;
	double rate = 10*(Double.parseDouble(jTextField2.getText()));
	rate /= (double) fps;
	jPanel1.rate = rate;
	jPanel1.particles = Integer.parseInt(jTextField1.getText());
	
	//change pull rate
	
	//Now make the new GlEventListener
    jPanel1.renderableCanvas.removeGLEventListener(jPanel1.listener);
    jPanel1.listener = new stretchingEventListener(Integer.parseInt(particles), rate);
    jPanel1.renderableCanvas.addGLEventListener(jPanel1.listener);
	System.out.println("reset performed");
}

//start operation :pause
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (jPanel1.animator.isAnimating()) {
    	jPanel1.animator.stop();
    	System.out.println("paused the animator");
    } else {
    	jPanel1.animator.start();
    	System.out.println("started the animator");
    }
}

private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
    if(evt.getKeyCode() == evt.VK_F1) {
        jPanel1.listener.zdistance -= 10;
    }
    if (evt.getKeyCode()==evt.VK_F2) {
    	jPanel1.listener.zdistance += 10;
    }
    if(evt.getKeyCode() == evt.VK_UP) {
        jPanel1.listener.ydistance += 10;
    }
    if (evt.getKeyCode()==evt.VK_DOWN) {
    	jPanel1.listener.ydistance -= 10;
    }
    if(evt.getKeyCode() == evt.VK_LEFT) {
        jPanel1.listener.xdistance -= 10;
    }
    if (evt.getKeyCode()==evt.VK_RIGHT) {
    	jPanel1.listener.xdistance += 10;
    }
}

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    // TODO add your handling code here:
    System.out.println("the text entered worked");
    System.out.println(jTextField1.getText());
}//GEN-LAST:event_jTextField1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StretchingMain().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private stretchingAnimationPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    
}
